config/routes.rb
Rails.application.routes.draw do

  get "rooms/add", :to => "rooms#add"

  get "rooms/edit", :to => "rooms#edit"

  get "rooms/index", :to => "rooms#index"

  resources :members
  resources :reservations
  resources :notifications
  post "notifications" => "notifications#create"
  delete "notifications" => "notifications#destroy"
  root :to => "sessions#login"
  get "signup", :to => "members#index"
  get "login", :to => "sessions#login"
  post "login_attempt", :to => "sessions#login_attempt"
  get "createadmin", :to => "members#create_admin"
  get "showadmins", :to => "members#show_admin"
  get "showmembers", :to => "members#show_member"
  get "logout", :to => "sessions#logout"
  get "home", :to => "sessions#home"
  get "adminhome", :to => "sessions#adminhome"
  get "profile", :to => "sessions#profile"
  get "setting", :to => "sessions#setting"
  get "logout", :to => "sessions#logout"
  get "search", :to => "sessions#search"
  get "booking",   :to => "reservations#book"
  get "delete", :to => "reservations#destroy"
  get "settings", :to => "sessions#settings"
  post "update", :to => "members#updateuser"
  post "rooms/add"
  post "rooms/create" => "rooms#create"
  resources :rooms, :only => [:add, :create]
  match '/rooms' => 'rooms#add', :via => :post
  resources :rooms do
    collection do
      get 'showall'

    end
  end

end

app/models/room.rb
class Room < ActiveRecord::Base
  validates :building,  :presence => true
  validates :roomnumber, :presence => true, :uniqueness => {:scope => :building}
  validates :size, :presence => true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    if session[:user_id]
      @rooms = Room.all
    else
      redirect_to :action => "login", :controller => "sessions"
    end

  end

  def show
    @room = Room.find(params[:id])
    @reservations = Reservation.find_by_sql(["select * from reservations where roomid = :id order by time_start desc", {:id => params[:id] }])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @room }
    end
  end

  def add
    @room = Room.new
  end

  def edit
    @room = Room.find(params[:id])
  end

  def create
    @room = Room.new(room_params)

    if @room.save
      redirect_to @room
    else
      flash[:notice]="Room number already exists"
      render 'add'
    end
  end

  def update
    @room = Room.find(params[:id])

    if @room.update(room_params)

      redirect_to @room
    else
      render 'edit'
    end
  end

  def destroy
    @room = Room.find(params[:id])
    Reservation.where(:roomid => params[:id]).destroy_all
    @room.destroy
    redirect_to rooms_path
  end

  private
  def room_params
    params.require(:room).permit(:roomnumber, :size, :building)
  end

  def delete
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/add.html.erb
<%
  if session[:is_admin]
%>
    <% content_for :title, "Add new room" %>

    <!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Library Rooms</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <a href="https://github.com/mrnayak/library">Github</a>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

<div class="container" style="background: #ffffff; min-height: 600px; max-width: 1200px; ">

  <div class="row">
    <div class="col-md-8">
      <img src="/assets/drawing.png" style="padding: 10px;"/>
      <div class="jumbotron">
        <legend>Add Rooms</legend>
        <%= form_tag({:action => :create, :method => :post}, {:class => 'form-horizontal'}) %>
        <% flash.each do |key, value| %>
            <div class="row omb_row-sm-offset-3 no-gutter m-a-3">
              <div class="col-xs-12 col-sm-6">
                <%= content_tag(:span, value, :class => "label label-danger") %>
              </div>
            </div>
            <br/>
        <% end %>
        <% flash.clear %>
        <div class="form-group">
          <label for="roomNumber" class="col-lg-2 control-label">Room Number</label>
          <div class="col-lg-4">
            <input type="text" name="room[roomnumber]" class="form-control" id="roomNumber" placeholder="Room Number">
          </div>
        </div>

        <div class="form-group">
          <label for="select" class="col-lg-2 control-label">Building</label>
          <div class="col-lg-4">
            <select class="form-control" id="select" name="room[building]">
              <option value="DH-Hill">DH Hill Library</option>
              <option value="James-Hunt">Dr James Hunt Library</option>
            </select>
          </div>

          <label for="select" class="col-lg-2 control-label">Rooms Type</label>
          <div class="col-lg-4">
            <select class="form-control" id="select" name="room[size]">
              <option value="4">Small-4</option>
              <option value="6">Medium-6</option>
              <option value="12">Large-12</option>
            </select>
          </div>
        </div>
        <div class="form-group">
          <div class="col-lg-10 col-lg-offset-2">
            <button type="reset" class="btn btn-default">Reset</button>
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="/adminhome">Home</a></li>
        <li><a href="/settings">Settings</a></li>
        <li><a href="/rooms">Manage Rooms</a></li>
        <li><a href="/showadmins">Manage Admins</a></li>
        <li><a href="/showmembers">Manage Members</a></li>
        <li><a href=/logout>Log out</a></li>
      </ul>
    </div>
  </div>
</div>
<!-- /.container -->
<% else %>
    <script type="application/javascript"> window.location.href = "/home";</script>
    <!-- /.container -->
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Rooms</h1>
 
<%= form_for :room, url: rooms_path(@room) do |f| %>

  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@room.errors.count, "error") %> prohibited
        this room from being saved:
      </h2>
      <ul>
        <% @room.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
 <p>
    <%= f.label :Room_no %><br>
    <%= f.text_field :room_no %>
  </p>
 
  <p>
    <%= f.label :Size %><br>
    <%= f.select :size, [['Small-4','4'],['Medium-6','6'],['Large-12','12']] %>
  </p>
  
    <%= f.label :Building %><br>
    <%= f.select :building, ['DHHill','JamesHunt'] %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', room_path %>

app/views/rooms/index.html.erb
<% content_for :title, "Manage Rooms" %>

<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Library Rooms</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <a href="https://github.com/mrnayak/library">Github</a>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

<div class="container" style="background: #ffffff; min-height: 600px; max-width: 1200px; ">

  <div class="row">
    <div class="col-md-8">
      <img src="/assets/drawing.png" style="padding: 10px;"/>

      <% if session[:is_admin] %> <a href="/rooms/add" class="btn btn-primary btn-sm">Create</a>
      <% end %>
      <table class="table table-striped table-hover ">
        <thead>
        <tr>
          <th>Room number</th>
          <th>Size</th>
          <th>Building</th>
          <th>Schedule</th>
          <% if session[:is_admin] %>
              <th>Delete</th>
          <% end %>
        </tr>
        </thead>
        <tbody>
        <% @rooms.each do |room| %>
            <tr>
              <td><%= room.roomnumber %></td>
              <td><%= room.size %></td>
              <td><%= room.building %></td>
              <td>
                <a href="<%= room_path(room) %>" style="color:#222;"> <i class="fa fa-calendar" aria-hidden="true"></i></a>
              </td>
              <td>
                <% if session[:is_admin] %>
                    <a href="<%= room_path(room) %>" style="color:#222;" data-confirm="Are you sure?" data-method="delete" rel="nofollow">
                      <i class="fa fa-trash" aria-hidden="true"></i></a></td>
                <% end %>
                </tr>
        <% end %>
        <tr>
        </tr>
        <tr>
        </tr>
        </tbody>
      </table>
      <i class="icon-edit"></i>
    </div>
    <div class="col-md-4">
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="/adminhome">Home</a></li>
        <li><a href="/settings">Settings</a></li>
        <% if session[:is_admin] %>
            <li><a href="/rooms">Manage Rooms</a></li>
            <li><a href="/showadmins">Manage Admins</a></li>
            <li><a href="/showmembers">Manage Members</a></li>
            <li><a href="/members/<%= session[:user_id] %>">My Profile</a></li>
        <% else %>
            <li><a href="/rooms">Rooms</a></li>
            <li><a href="/members/<%= session[:user_id] %>">My Profile</a></li>
        <% end %>
        <li><a href=/logout>Log out</a></li>
      </ul>
    </div>
  </div>
</div>
<!-- /.container -->

app/views/rooms/new.html.erb
<%= form_for :room, url: rooms_path do |f| %>
 <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@room.errors.count, "error") %> prohibited
        this room from being saved:
      </h2>
      <ul>
        <% @room.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :Roomnumber %><br>
    <%= f.text_field :room_no %>
  </p>
 
  <p>
    <%= f.label :Size %><br>
    <%= f.select :size, [['Small-4','4'],['Medium-6','6'],['Large-12','12']] %>
  </p>
  
    <%= f.label :Building %><br>
    <%= f.select :building, ['DHHill','JamesHunt'] %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/rooms/show.html.erb
<% content_for :title, "Manage Rooms" %>

<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Library Rooms</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <a href="https://github.com/mrnayak/library">Github</a>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

<div class="container" style="background: #ffffff; min-height: 600px; max-width: 1200px; ">

  <div class="row">
    <div class="col-md-8">
      <img src="/assets/drawing.png" style="padding: 10px;"/>
      <h5>Room Number : <%=@room.roomnumber%> | Building : <%=@room.building%> </h5>
      <table class="table table-striped table-hover "><thead>
      <tr>
        <th>Start Time</th>
        <th>End Time</th>
      </tr>
      </thead><tbody>
      <% @reservations.each do |reservation| %>
          <tr>
            <td><%= reservation.time_start %></td>
            <td><%= reservation.time_end %></td>
            <% if session[:is_admin] %>
           <td><a style="color: #222;" href ="/members/<%=reservation.userid %>">Click here to view user</a></td>

            <% if DateTime.parse(reservation.time_end.to_s).to_datetime > DateTime.now.to_datetime %>
                <% if DateTime.parse(reservation.time_start.to_s).to_datetime < DateTime.now.to_datetime %>
                    <td><a href="<%=reservation_path(reservation) %>" class="btn btn-warning btn-sm" data-confirm="Are you sure?" data-method="put" rel="nofollow">Release</a></td>
                <% else %>
                    <td><a href="<%=reservation_path(reservation) %>" class="btn btn-danger btn-sm" data-confirm="Are you sure?" data-method="delete" rel="nofollow">Cancel</a></td>
                <% end %>
            <% else %>
                <td></td>
            <% end %>
            <% end %>
          </tr>
      <% end %>
      <tr>
      </tr>
      <tr>
      </tr>
      </tbody>
      </table>
      <i class="icon-edit"></i>
    </div>
    <div class="col-md-4">
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="/adminhome">Home</a></li>
        <li><a href="/settings">Settings</a></li>
        <% if session[:is_admin] %>
            <li><a href="/rooms">Manage Rooms</a></li>
            <li><a href="/showadmins">Manage Admins</a></li>
            <li><a href="/showmembers">Manage Members</a></li>
            <li><a href="/members/<%= session[:user_id] %>">My Profile</a></li>
        <% else %>
            <li><a href="/rooms">Rooms</a></li>
            <li><a href="/members/<%= session[:user_id] %>">My Profile</a></li>
        <% end %>
        <li><a href=/logout>Log out</a></li>
        <li><a href="/showmembers">Manage Members</a></li>
      </ul>
    </div>
  </div>
</div>
<!-- /.container -->