config/routes.rb
Rails.application.routes.draw do

  get "rooms/add", :to => "rooms#add"

  get "rooms/edit", :to => "rooms#edit"

  get "rooms/index", :to => "rooms#index"

  resources :members
  resources :reservations
  resources :notifications
  post "notifications" => "notifications#create"
  delete "notifications" => "notifications#destroy"
  root :to => "sessions#login"
  get "signup", :to => "members#index"
  get "login", :to => "sessions#login"
  post "login_attempt", :to => "sessions#login_attempt"
  get "createadmin", :to => "members#create_admin"
  get "showadmins", :to => "members#show_admin"
  get "showmembers", :to => "members#show_member"
  get "logout", :to => "sessions#logout"
  get "home", :to => "sessions#home"
  get "adminhome", :to => "sessions#adminhome"
  get "profile", :to => "sessions#profile"
  get "setting", :to => "sessions#setting"
  get "logout", :to => "sessions#logout"
  get "search", :to => "sessions#search"
  get "booking",   :to => "reservations#book"
  get "delete", :to => "reservations#destroy"
  get "settings", :to => "sessions#settings"
  post "update", :to => "members#updateuser"
  post "rooms/add"
  post "rooms/create" => "rooms#create"
  resources :rooms, :only => [:add, :create]
  match '/rooms' => 'rooms#add', :via => :post
  resources :rooms do
    collection do
      get 'showall'

    end
  end

end

app/models/member.rb
class Member < ActiveRecord::Base
  attr_accessor :password_field

  EMAIL_PATTTERN = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i

  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_PATTTERN

  validates :password_field, :presence => true

  validates_length_of :password_field, :in => 6..20, :on => :create

  validates :name, :presence => true

  before_save :encrypt_password

  protected

  def encrypt_password
    self.password = Digest::SHA1.hexdigest(password_field).to_s
  end

  def self.authenticate(email="", login_password="")
      member = Member.find_by_email(email)
    if member && member.match_password(login_password)
      return member
    else
      return false
    end
  end

  def self.getmember(id="")
    member = Member.find_by_id(id)
    return member
  end

  public
  def match_password(login_password="")
    password == Digest::SHA1.hexdigest(login_password).to_s
  end
end

app/controllers/members_controller.rb
require 'digest/sha1'

class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  def index
      @members = Member.all
  end

  def updateuser
    @member = Member.authenticate(params[:member][:email], params[:member][:old_password_field])

    if (@member.id != session[:user_id])
      flash[:notice]="Invalid email id entered"
      redirect_to :controller => 'sessions', :action => 'settings'
      return
    end

    if (@member)
      if @member.update(member_param)
        flash[:notice]="Profile details updated"
        redirect_to :controller => 'sessions', :action => 'home'
      else
        flash[:notice]="Please enter valid email id and password"
        redirect_to :controller => 'sessions', :action => 'settings'
      end
    else
      flash[:notice]="Please enter valid email id and password"
      redirect_to :controller => 'sessions', :action => 'settings'
    end
  end

  def create
    @member = Member.new(member_param)
    if !session[:is_admin] && @member.is_admin
      redirect_to :action => :index
    else
      if @member.save
        if @member.is_admin
          redirect_to :controller => 'sessions', :action => 'adminhome'
        else
          redirect_to :controller => 'sessions', :action => 'login'
        end
      else
        flash[:notice]="Please enter valid email id or password"
        redirect_to :action => :index
      end
    end
  end

  def destroy
    if session[:is_admin]
      @member = Member.find(params[:id])
      is_admin = @member.is_admin
      @member.destroy
      Reservation.where(:userid => params[:id]).destroy_all
      if is_admin
        redirect_to :action => :show_admin
      else
        redirect_to :action => :show_member
      end
    end
  end

  def show
    if session[:is_admin] || (params[:id].to_s == session[:user_id].to_s)
      @member = Member.find(params[:id])
      @notifications = Notification.find_by_sql(["select * from notifications where userid = :uid order by time_start desc", {:uid => params[:id]}])
      @reservations = Reservation.find_by_sql(["select * from reservations where userid = :uid order by time_start desc", {:uid => params[:id]}])
    else
      redirect_to :action => :home, :controller => 'sessions'
    end
  end
  def new
    @member = Member.new
  end

  def create_admin
    @member = Member.new
  end

  def show_admin
    if session[:user_id]
      @members = Member.where("is_admin = true")
    else
      redirect_to :action => "login", :controller => "sessions"
    end
  end

  def show_member
    if session[:user_id]
      @members = Member.where("is_admin != true")
    else
      redirect_to :action => "login", :controller => "sessions"
    end
  end

  private

  def set_member
    @member = Member.find(params[:id])
  end

  def member_param
    params.require(:member).permit(:email, :name, :password_field, :is_admin)
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/create_admin.html.erb
<% if session[:user_id] %>
    <% content_for :title, "Create new Admin" %>

    <div class="container" style="background: #fff; margin-top: 1%; border-radius: 25px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
      <div class="row" style="padding: 20px">


        <img src="/assets/drawing.png" style="padding: 10px;"/>
        <%= form_tag({:action => :create, :method => :post}, {:class => 'form-horizontal'}) %>
        <div class="form-group">
          <label for="inputName" class="col-lg-2 control-label">Name</label>
          <div class="col-lg-10">
            <%= text_field "member", "name", "class" => "form-control", "placeholder" => "Full Name" %>
          </div>
        </div>
        <div class="form-group">
          <label for="inputEmail" class="col-lg-2 control-label">Email</label>
          <div class="col-lg-10">
            <%= text_field "member", "email", "class" => "form-control", "placeholder" => " @ncsu.edu" %>
          </div>
        </div>
        <div class="form-group">
          <label for="inputPassword" class="col-lg-2 control-label">Password</label>
          <div class="col-lg-10">
            <%= password_field "member", "password_field", "class" => "form-control" %>
          </div>
        </div>
        <input type="hidden" name="member[is_admin]" value="true">
        <div class="form-group">
          <div class="col-lg-10 col-lg-offset-2">
            <button type="reset" class="btn btn-default">Reset</button>
            <button type="submit" class="btn btn-primary">Create Admin</button>
          </div>
        </div>
        </form>
      </div>
    </div>
<% else %>
    <script type="application/javascript"> window.location.href = "/login"</script>
<% end %>

app/views/members/form.html.erb
<form action="members" method="post">
 email <input name="email" type="text"/>
  name <input name = "name" type="text"/>
 password <input name="password" type="text"/>
  <input name="submit" type = "submit">
</form>

app/views/members/index.html.erb
<% content_for :title, "Sign up" %>

<div class="container" style="background: #fff; margin-top: 1%; border-radius: 25px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">

  <% flash.each do |key, value| %>
      <div class="col-md-10 col-sm-12 p-a-3">
        <div class="row omb_row-sm-offset-3 no-gutter m-a-3">
          <div class="col-xs-12 col-sm-6">
            <%= content_tag(:span, value, :class => "label label-danger") %>
          </div>
        </div></div>
  <% end %>
  <% flash.clear %>
  <br/>
  <div class="row" style="padding: 20px">

    <img src="/assets/drawing.png" style="padding: 10px;"/>
      <%= form_tag({:action => :create, :method => :post}, {:class => 'form-horizontal'}) %>
      <div class="form-group">
        <label for="inputName" class="col-lg-2 control-label">Name</label>
        <div class="col-lg-10">
          <%= text_field "member", "name", "class" => "form-control", "placeholder" => "Full Name" %>
        </div>
      </div>
      <div class="form-group">
        <label for="inputEmail" class="col-lg-2 control-label">Email</label>
        <div class="col-lg-10">
          <%= text_field "member", "email", "class" => "form-control" , "placeholder" => " @ncsu.edu"%>
        </div>
      </div>
      <div class="form-group">
        <label for="inputPassword" class="col-lg-2 control-label">Password</label>
        <div class="col-lg-10">
          <%= password_field "member", "password_field", "class" => "form-control" %>
        </div>
      </div>
    <input type="hidden" name="member[is_admin]" value="false">
      <div class="form-group">
        <div class="col-lg-10 col-lg-offset-2">
          <button type="reset" class="btn btn-default">Reset</button>
          <button type="submit" class="btn btn-primary">Sign Up</button>
        </div>
      </div>
      </form>
  </div>
</div>

app/views/members/show.html.erb
<% content_for :title, "Manage members" %>
<% if session[:is_admin] || @member.id == session[:user_id] %>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Library Rooms</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <a href="https://github.com/mrnayak/library">Github</a>
            </li>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
    </nav>

    <div class="container" style="background: #ffffff; min-height: 600px; max-width: 1200px; ">

      <div class="row">
        <div class="col-md-8">
          <img src="/assets/drawing.png" style="padding: 10px;"/>
          <table class="table table-striped table-hover ">
            <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <% if session[:is_admin] && session[:user_id] != @member.id%>
              <th>Delete</th>
                  <% end %>
            </tr>
            </thead>
            <tbody>
            <tr>
              <td><%= @member.name %></td>
              <td><%= @member.email %></td>
              <% if session[:is_admin] && session[:user_id] != @member.id %>
              <td>
                <a href="<%= member_path(@member) %>" style="color:#222;" data-confirm="Are you sure?" data-method="delete" rel="nofollow">
                  <i class="fa fa-trash" aria-hidden="true"></i></a></td> <% end %>
            </tr>
            <tr>
            </tr>
            <tr>
            </tr>
            </tbody>
          </table>
          <i class="icon-edit"></i>
        </div>
        <div class="col-md-4">
          <ul class="nav nav-pills nav-stacked">
            <li class="active"><a href="/adminhome">Home</a></li>
            <li><a href="/settings">Settings</a></li>
            <% if session[:is_admin] %>
                <li><a href="/rooms">Manage Rooms</a></li>
                <li><a href="/showadmins">Manage Admins</a></li>
                <li><a href="/showmembers">Manage Members</a></li>
                <li><a href="/members/<%= session[:user_id] %>">My Profile</a></li>
            <% else %>
                <li><a href="/rooms">Rooms</a></li>
                <li><a href="/members/<%= session[:user_id] %>">My Profile</a></li>
            <% end %>
            <li><a href=/logout>Log out</a></li>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="col-md-8">
          <h4><i class="fa fa-calendar" aria-hidden="true"></i> Booking History</h4>
          <table class="table table-striped table-hover ">
            <thead>
            <tr>
              <th>Room</th>
              <th>Start Time</th>
              <th>End Time</th>
              <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <% @reservations.each do |reservation| %>
                <tr>
                  <td><a style="color: #222;" href="/rooms/<%= reservation.roomid %>">Room Id
                    #<%= reservation.roomid %></a></td>
                  <td><%= reservation.time_start %></td>
                  <td><%= reservation.time_end %></td>
                  <% if DateTime.parse(reservation.time_end.to_s).to_datetime > DateTime.now.to_datetime %>
                      <% if DateTime.parse(reservation.time_start.to_s).to_datetime < DateTime.now.to_datetime %>
                          <td>
                            <a href="<%= reservation_path(reservation) %>" class="btn btn-warning btn-sm" data-confirm="Are you sure?" data-method="put" rel="nofollow">Release</a>
                          </td>
                      <% else %>
                          <td>
                            <a href="<%= reservation_path(reservation) %>" class="btn btn-danger btn-sm" data-confirm="Are you sure?" data-method="delete" rel="nofollow">Cancel</a>
                          </td>
                      <% end %>
                  <% else %>
                      <td></td>
                  <% end %>
                </tr>
            <% end %>
            <tr>
            </tr>
            <tr>
            </tr>
            </tbody>
          </table>
          <i class="icon-edit"></i>
        </div>
        <div class="col-md-4">
          <ul class="nav nav-pills">
            <li>Notifications <span class="badge"><%=@notifications.size%></span></li>
          </ul>
          <%@notifications.each do |notification|%>
          <div class="alert alert-dismissible alert-success">
            <a href = "<%= notification_path(notification) %>" class="close" data-method="delete" rel="nofollow">&times;</a>
            <strong><%=notification.text%></strong>
          </div>
          <% end %>
        </div>
      </div>
    </div>
<% end %>
<!-- /.container -->

app/views/members/show_admin.html.erb
<% if session[:is_admin] %>
<% content_for :title, "Manage Admins" %>

<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Library Rooms</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <a href="https://github.com/mrnayak/library">Github</a>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

<div class="container" style="background: #ffffff; min-height: 600px; max-width: 1200px; ">

  <div class="row">
    <div class="col-md-8">
      <img src="/assets/drawing.png" style="padding: 10px;"/>
      <a href="createadmin" class="btn btn-primary btn-sm">Create</a>
      <table class="table table-striped table-hover "><thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Delete</th>
      </tr>
      </thead><tbody>
      <% @members.each do |member| %>
      <% if session[:user_id] != member.id && member.email != "admin@ncsu.edu" %>
          <tr>
            <td><%= member.name %></td>
            <td><%= member.email %></td>
            <td><a href="<%= member_path(member) %>" style="color:#222;" data-confirm="Are you sure?" data-method="delete" rel="nofollow"> <i class="fa fa-trash" aria-hidden="true"></i></a></td>
          </tr>
      <% end %>
      <% end %>
      <tr>
      </tr>
      <tr>
      </tr>
      </tbody>
      </table>
      <i class="icon-edit"></i>
    </div>
    <div class="col-md-4">
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="/adminhome">Home</a></li>
        <li><a href="settings">Settings</a></li>
        <% if session[:is_admin] %>
            <li><a href="/rooms">Manage Rooms</a></li>
            <li><a href="/showadmins">Manage Admins</a></li>
            <li><a href="/showmembers">Manage Members</a></li>
            <li><a href="/members/<%= session[:user_id] %>">My Profile</a></li>
        <% else %>
            <li><a href="/rooms">Rooms</a></li>
            <li><a href="/members/<%= session[:user_id] %>">My Profile</a></li>
        <% end %>
        <li><a href=/logout>Log out</a></li>
      </ul>
    </div>
  </div>
</div>
<!-- /.container -->
<% else %>
    <script type="application/javascript">window.location.href ="/home";</script>
<% end %>

app/views/members/show_member.html.erb
<% if session[:is_admin] %>
<% content_for :title, "Manage members" %>

<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Library Rooms</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <a href="https://github.com/mrnayak/library">Github</a>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

<div class="container" style="background: #ffffff; min-height: 600px; max-width: 1200px; ">

  <div class="row">
    <div class="col-md-8">
      <img src="/assets/drawing.png" style="padding: 10px;"/>
      <a href="/signup" class="btn btn-primary btn-sm">Create new member</a>
      <table class="table table-striped table-hover "><thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>History/Schedule</th>
        <th>Delete</th>
      </tr>
      </thead><tbody>
      <% @members.each do |member| %>
              <tr>
                <td><%= member.name %></td>
                <td><%= member.email %></td>
                <td><a href="<%= member_path(member) %>" style="color:#222;" > <i class="fa fa-calendar" aria-hidden="true"></i></a></td>
                <td><a href="<%= member_path(member) %>" style="color:#222;" data-confirm="Are you sure?" data-method="delete" rel="nofollow"> <i class="fa fa-trash" aria-hidden="true"></i></a></td>
              </tr>
      <% end %>
      <tr>
      </tr>
      <tr>
      </tr>
      </tbody>
      </table>
      <i class="icon-edit"></i>
    </div>
    <div class="col-md-4">
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="/adminhome">Home</a></li>
        <li><a href="/settings">Settings</a></li>
        <% if session[:is_admin] %>
            <li><a href="/rooms">Manage Rooms</a></li>
            <li><a href="/showadmins">Manage Admins</a></li>
            <li><a href="/showmembers">Manage Members</a></li>
            <li><a href="/members/<%= session[:user_id] %>">My Profile</a></li>
        <% else %>
            <li><a href="/rooms">Rooms</a></li>
            <li><a href="/members/<%= session[:user_id] %>">My Profile</a></li>
        <% end %>
        <li><a href=/logout>Log out</a></li>
      </ul>
    </div>
  </div>
</div>
<!-- /.container -->
<% else %>
<script type="application/javascript">window.location.href ="/home";</script>
<% end %>